import { Product } from 'reducers/tierList';

const products: Record<string, Product> = {
  1: {
    id: '1',
    name: 'Fjallraven - Foldsack No. 1 Backpack, Fits 15 Laptops',
    price: 109.95,
    vendor: 'Your',
    image: 'https://fakestoreapi.com/img/81fPKd-2AYL._AC_SL1500_.jpg',
  },
  2: {
    id: '2',
    name: 'Mens Casual Premium Slim Fit T-Shirts',
    price: 22.3,
    vendor: 'Slim',
    image:
      'https://fakestoreapi.com/img/71-3HjGNDUL._AC_SY879._SX._UX._SY._UY_.jpg',
  },
  3: {
    id: '3',
    name: 'Mens Cotton Jacket',
    price: 55.99,
    vendor: 'Great',
    image: 'https://fakestoreapi.com/img/71li-ujtlUL._AC_UX679_.jpg',
  },
  4: {
    id: '4',
    name: 'Mens Casual Slim Fit',
    price: 15.99,
    vendor: 'The',
    image: 'https://fakestoreapi.com/img/71YXzeOuslL._AC_UY879_.jpg',
  },
  5: {
    id: '5',
    name: "John Hardy Women's Legends Naga Gold & Silver Dragon Station Chain Bracelet",
    price: 695,
    vendor: 'From',
    image: 'https://fakestoreapi.com/img/71pWzhdJNwL._AC_UL640_QL65_ML3_.jpg',
  },
  6: {
    id: '6',
    name: 'Solid Gold Petite Micropave',
    price: 168,
    vendor: 'Satisfaction',
    image: 'https://fakestoreapi.com/img/61sbMiUnoGL._AC_UL640_QL65_ML3_.jpg',
  },
  7: {
    id: '7',
    name: 'White Gold Plated Princess',
    price: 9.99,
    vendor: 'Classic',
    image: 'https://fakestoreapi.com/img/71YAIFU48IL._AC_UL640_QL65_ML3_.jpg',
  },
  8: {
    id: '8',
    name: 'Pierced Owl Rose Gold Plated Stainless Steel Double',
    price: 10.99,
    vendor: 'Rose',
    image: 'https://fakestoreapi.com/img/51UDEzMJVpL._AC_UL640_QL65_ML3_.jpg',
  },
  9: {
    id: '9',
    name: 'WD 2TB Elements Portable External Hard Drive - USB 3.0',
    price: 64,
    vendor: 'USB',
    image: 'https://fakestoreapi.com/img/61IBBVJvSDL._AC_SY879_.jpg',
  },
  10: {
    id: '10',
    name: 'SanDisk SSD PLUS 1TB Internal SSD - SATA III 6 Gb/s',
    price: 109,
    vendor: 'Easy',
    image: 'https://fakestoreapi.com/img/61U7T1koQqL._AC_SX679_.jpg',
  },
  11: {
    id: '11',
    name: 'Silicon Power 256GB SSD 3D NAND A55 SLC Cache Performance Boost SATA III 2.5',
    price: 109,
    vendor: '3D',
    image: 'https://fakestoreapi.com/img/71kWymZ+c+L._AC_SX679_.jpg',
  },
  12: {
    id: '12',
    name: 'WD 4TB Gaming Drive Works with Playstation 4 Portable External Hard Drive',
    price: 114,
    vendor: 'Expand',
    image: 'https://fakestoreapi.com/img/61mtL65D4cL._AC_SX679_.jpg',
  },
  13: {
    id: '13',
    name: 'Acer SB220Q bi 21.5 inches Full HD (1920 x 1080) IPS Ultra-Thin',
    price: 599,
    vendor: '21',
    image: 'https://fakestoreapi.com/img/81QpkIctqPL._AC_SX679_.jpg',
  },
  14: {
    id: '14',
    name: 'Samsung 49-Inch CHG90 144Hz Curved Gaming Monitor (LC49HG90DMNXZA) – Super Ultrawide Screen QLED',
    price: 999.99,
    vendor: '49',
    image: 'https://fakestoreapi.com/img/81Zt42ioCgL._AC_SX679_.jpg',
  },
  15: {
    id: '15',
    name: "BIYLACLESEN Women's 3-in-1 Snowboard Jacket Winter Coats",
    price: 56.99,
    vendor: 'Note',
    image: 'https://fakestoreapi.com/img/51Y5NI-I5jL._AC_UX679_.jpg',
  },
  16: {
    id: '16',
    name: "Lock and Love Women's Removable Hooded Faux Leather Moto Biker Jacket",
    price: 29.95,
    vendor: '100%',
    image: 'https://fakestoreapi.com/img/81XH0e8fefL._AC_UY879_.jpg',
  },
  17: {
    id: '17',
    name: 'Rain Jacket Women Windbreaker Striped Climbing Raincoats',
    price: 39.99,
    vendor: 'Lightweight',
    image: 'https://fakestoreapi.com/img/71HblAHs5xL._AC_UY879_-2.jpg',
  },
  18: {
    id: '18',
    name: "MBJ Women's Solid S'hort Sleeve Boat Neck V",
    price: 9.85,
    vendor: '95',
    image: 'https://fakestoreapi.com/img/71z3kpMAYsL._AC_UY879_.jpg',
  },
  19: {
    id: '19',
    name: "Opna Women's Short Sleeve Moisture",
    price: 7.95,
    vendor: '100',
    image: 'https://fakestoreapi.com/img/51eg55uWmdL._AC_UX679_.jpg',
  },
  20: {
    id: '20',
    name: 'DANVOUY Womens T Shirt Casual Cotton Short',
    price: 12.99,
    vendor: '95',
    image: 'https://fakestoreapi.com/img/61pHAEJ4NML._AC_UX679_.jpg',
  },
};

export default products;
